# Numpy
* 행렬 연산을 쉽게 할 수 있도록 해주는 패키지
* https://numpy.org/doc/stable/
---
### 오늘 배울 것
1. numpy array란?
2. shape, indexing
3. pandas DataFrame을 numpy array로 변환하기
4. 다양한 연산들

In [1]:
import numpy as np

In [3]:
arr = np.random.rand(6, 4)
arr

array([[0.71962142, 0.00134539, 0.5563375 , 0.12454822],
       [0.41065505, 0.30468065, 0.68248128, 0.75139661],
       [0.06027933, 0.05184555, 0.97791964, 0.4697728 ],
       [0.34617232, 0.53749285, 0.89843185, 0.55217917],
       [0.69897594, 0.51361919, 0.98554258, 0.19767595],
       [0.04145383, 0.06946319, 0.01245592, 0.31931875]])

In [4]:
# get dimension of array
arr.shape

(6, 4)

In [5]:
# selecting indecies of array
print(arr[:, 3])
print('--------------------------------------------------------------------')
print(arr[1, 1])
print('--------------------------------------------------------------------')
print(arr[0, :])
print('--------------------------------------------------------------------')
print(arr[:2, :3])
print('--------------------------------------------------------------------')
print(arr[[1, 3], 2])

[0.12454822 0.75139661 0.4697728  0.55217917 0.19767595 0.31931875]
--------------------------------------------------------------------
0.30468064570860587
--------------------------------------------------------------------
[0.71962142 0.00134539 0.5563375  0.12454822]
--------------------------------------------------------------------
[[0.71962142 0.00134539 0.5563375 ]
 [0.41065505 0.30468065 0.68248128]]
--------------------------------------------------------------------
[0.68248128 0.89843185]


In [7]:
import pandas as pd

# Read file (txt file)
table = pd.read_csv('./data/sample_01.txt', delimiter='\t')
table = table.set_index('ID_REF')
table

GSM437093  GSM437094  GSM437095  GSM437096  GSM437097  \
ID_REF                                                                
1007_s_at     11.658060  11.627632  11.209226  11.770620  11.097194   
1053_at        8.845589   8.625595   8.234096   8.727833   8.521389   
117_at         7.450960   7.342564   8.122719   7.285359   7.820522   
121_at         9.907034   9.957431   9.889233   9.594032   9.551032   
1255_g_at      4.891556   4.898858   4.769176   4.841742   4.802824   
...                 ...        ...        ...        ...        ...   
1552384_a_at   6.975383   7.042849   6.965261   6.778810   6.856942   
1552386_at     5.222090   5.600755   5.477280   5.105544   5.050946   
1552388_at     7.276907   7.442435   7.168456   7.598248   7.335759   
1552389_at     5.093532   5.381494   5.140635   5.107301   5.873668   
1552390_a_at   4.547978   4.544477   4.586694   4.422706   6.535929   

              GSM437098  GSM437099  GSM437100  GSM437101  GSM437102  ...  \
ID_REF                                                               ...   
1007_s_at     11.217040  11.480605  11.174613  11.157401  11.215819  ...   
1053_at        8.812260   8.578217   8.408970   9.016806   8.548101  ...   
117_at         7.513008   7.595940   7.606444   7.343781   8.775246  ...   
121_at         9.682159   9.951888   9.678011   9.826328   9.693594  ...   
1255_g_at      5.104819   4.877827   4.894545   4.927487   5.051599  ...   
...                 ...        ...        ...        ...        ...  ...   
1552384_a_at   6.850231   7.049125   7.031236   6.887568   6.797369  ...   
1552386_at     5.290673   5.472352   5.137203   5.209577   5.352782  ...   
1552388_at     7.214616   7.709489   7.594317   7.189670   7.184662  ...   
1552389_at     5.000425   5.329288   5.400619   5.344432   4.794404  ...   
1552390_a_at   4.462388   4.437473   5.279154   4.472019   4.261987  ...   

              GSM437260  GSM437261  GSM437262  GSM437263  GSM437264  \
ID_REF                                                                
1007_s_at     10.558947  11.497468  11.664038  11.013572  11.784416   
1053_at        8.669574   8.669394   8.848055   8.558723   9.522910   
117_at         7.724462   7.440434   7.663952   7.822330   7.439561   
121_at         9.832929  10.158157   9.844260   9.960091   9.785614   
1255_g_at      4.867194   4.836543   5.160730   4.977262   4.908078   
...                 ...        ...        ...        ...        ...   
1552384_a_at   7.023289   6.742468   6.496278   6.733683   6.883836   
1552386_at     6.392734   5.507826   5.327145   5.792986   5.220366   
1552388_at     7.470158   7.007965   7.233820   7.033575   7.414641   
1552389_at     5.583171   5.197203   5.349381   5.422553   5.335815   
1552390_a_at   4.740912   4.584616   6.302526   6.071731   4.647642   

              GSM437265  GSM437266  GSM437267  GSM437268  GSM437269  
ID_REF                                                               
1007_s_at     11.153646  11.263214  11.414354  11.233133  11.604788  
1053_at        9.183248   8.537171   9.203837   9.139161   8.969117  
117_at         7.642415   7.587165   7.608669   7.296488   7.427372  
121_at         9.846085   9.890658   9.751073   9.874834   9.851839  
1255_g_at      5.067716   5.054698   5.151886   4.891733   4.767123  
...                 ...        ...        ...        ...        ...  
1552384_a_at   6.860858   6.663199   6.586654   6.534249   6.259591  
1552386_at     5.357264   6.005586   5.340584   5.593049   5.261292  
1552388_at     7.190608   7.315107   7.073407   7.370955   6.734957  
1552389_at     4.941453   4.941202   4.889489   5.168128   5.049390  
1552390_a_at   4.357186   4.257088   4.034042   4.934642   4.499144  

[99 rows x 177 columns]

In [8]:
# Make np array from DataFrame

df_arr = np.array(table.loc['1007_s_at'])
print(df_arr)
print('shape : {}'.format(df_arr.shape))
print('--------------------------------------------------------------------')
df_arr = np.array(table.iloc[:2, :3])
print(df_arr)
print('shape : {}'.format(df_arr.shape))

[11.65806001 11.62763245 11.20922635 11.77062023 11.09719369 11.21703978
 11.48060517 11.17461338 11.15740074 11.21581862 11.51351401 11.55347172
 11.27166397 11.27834819 11.53304493 11.30160368 11.06511656 10.56564286
 11.65840705 10.99288223 11.38937222 11.38189053 11.30510026 11.78160567
 11.60236532 10.9635526  11.52013112 11.30543543 11.52316758 11.56479249
 11.28864141 11.71613445 11.57913792 10.97763412 11.1252792  11.52859722
 11.63241457 11.18680086 11.28721314 11.34328805 11.10550843 11.47100893
 11.26547413 11.55765966 11.12726454 11.43800368 11.383763   11.43508286
 11.14045412 11.36882297 10.8950259  11.72482451 11.2341227  10.94671741
 11.90722048 10.96110234 11.44330592 10.92876877 11.49330637 11.09660443
 11.16587355 11.52489246 10.86402874 11.07785031 11.11151232 11.7727096
 11.67644763 11.02105134 11.39575926 11.19269875 11.51176274 11.37563908
 11.21468481 11.13497148 11.14858416 11.6503364  11.15682674 11.5223139
 10.89064292 11.60920103 12.02237559 11.74584083 11.2

In [58]:
# Arithmetic Operations

arr1 = np.random.rand(2, 3)
arr2 = np.random.rand(2, 3)

print('ARR 1')
print(arr1, end='\n\n')
print('Arr 2')
print(arr2)
print('--------------------------------------------------------------------')
print(arr1 + arr2)
print('--------------------------------------------------------------------')
print(arr1 - arr2)
print('--------------------------------------------------------------------')
print(arr1 * arr2)
print('--------------------------------------------------------------------')
print(arr1 / arr2)

ARR 1
[[0.2421102  0.74578441 0.59172516]
 [0.32135211 0.84912758 0.01442639]]

Arr 2
[[0.15132587 0.61009785 0.23655756]
 [0.14562639 0.72819905 0.09699238]]
--------------------------------------------------------------------
[[0.39343607 1.35588226 0.82828272]
 [0.46697849 1.57732664 0.11141877]]
--------------------------------------------------------------------
[[ 0.09078433  0.13568655  0.3551676 ]
 [ 0.17572572  0.12092853 -0.08256599]]
--------------------------------------------------------------------
[[0.03663754 0.45500147 0.13997706]
 [0.04679735 0.6183339  0.00139925]]
--------------------------------------------------------------------
[[1.59992602 1.2224013  2.50140038]
 [2.20668877 1.16606521 0.14873736]]


In [9]:
# Operation : normalization

print(df_arr)
print('--------------------------------------------------------------------')
col_norm = np.linalg.norm(df_arr, axis=0).reshape(1,3)
print(col_norm)
cnorm_arr = df_arr / col_norm
print(cnorm_arr)
print('--------------------------------------------------------------------')
row_norm = np.linalg.norm(df_arr, axis=1).reshape(2,1)
print(row_norm)
rnorm_arr = df_arr / row_norm
print(rnorm_arr)

[[11.65806001 11.62763245 11.20922635]
 [ 8.84558887  8.62559451  8.23409564]]
--------------------------------------------------------------------
[[14.63402903 14.47766269 13.90852567]]
[[0.79664049 0.80314293 0.80592484]
 [0.60445342 0.5957864  0.59201786]]
--------------------------------------------------------------------
[[19.91880907]
 [14.84741237]]
[[0.58527897 0.58375139 0.56274581]
 [0.59576636 0.58094935 0.55458119]]


In [ ]:
# TODO : log2

# YOUR CODE HERE

